version: '3.7'

services:
    redis:
        image: redis:apline
        restart: always

    nginx:
        image: nginx:1.17.9
        restart: always

    web:
        image: frappe:agent
        restart: always
    
    worker:
        image: frappe:agent
        restart: always
    