apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frappe
  template:
    metadata:
      labels:
        app: frappe
    spec:
      containers:
      - name: frappe
        image: kamaleshseervi/frappelms
        command: ["bash", "/workspace/init.sh"]
